-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 03:20:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tifosi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tifosi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tifosi` DEFAULT CHARACTER SET utf8 ;
USE `tifosi` ;

-- -----------------------------------------------------
-- Table `tifosi`.`tifosi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`tifosi` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`ingredient` (
  `id_ingredient` INT NOT NULL AUTO_INCREMENT,
  `nom_ingredient` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`comprend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`comprend` (
  `ingredient` INT NULL,
  INDEX `ingredient` (`ingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`focaccia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`focaccia` (
  `id_focaccia` INT NOT NULL AUTO_INCREMENT,
  `nom_focaccia` VARCHAR(45) NOT NULL,
  `prix_focaccia` FLOAT NOT NULL,
  `comprend` INT NULL,
  PRIMARY KEY (`id_focaccia`),
  INDEX `comprend` (`comprend`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`achete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`achete` (
  `jour` DATE NOT NULL,
  `focaccia` INT NULL,
  INDEX `focaccia` (`focaccia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`est constitué`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`est constitué` (
  `focaccia` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`marque` (
  `idmarque` INT NOT NULL AUTO_INCREMENT,
  `nom_marque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`appartient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`appartient` (
  `marque` INT NULL,
  INDEX `marque` (`marque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`boisson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`boisson` (
  `id_boisson` INT NOT NULL AUTO_INCREMENT,
  `nom_boisson` VARCHAR(45) NOT NULL,
  `appartient` INT NULL,
  PRIMARY KEY (`id_boisson`),
  INDEX `appartient` (`appartient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`contient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`contient` (
  `boisson` INT NULL,
  INDEX `boisson` (`boisson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `nom_menu` VARCHAR(45) NOT NULL,
  `prix_menu` FLOAT NOT NULL,
  `constituer` INT NULL,
  `contient` INT NULL,
  PRIMARY KEY (`id_menu`),
  INDEX `constituer` (`constituer`),
  INDEX `contient` (`contient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`paye`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`paye` (
  `jour` DATE NOT NULL,
  `menu` INT NULL,
  INDEX `menu` (`menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom_client` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `cp_client` INT NOT NULL,
  `achete` INT NULL,
  `paye` INT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `achete` (`achete`),
  INDEX `paye` (`paye`) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
